
INSTALL_TARGET_PROCESSES = SpringBoard


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = pxy4sp

pxy4sp_FILES = Tweak.x
pxy4sp_CFLAGS = -fobjc-arc
pxy4sp_PRIVATE_FRAMEWORKS = WiFiKit


include $(THEOS_MAKE_PATH)/tweak.mk
